"""add kb_retrieval_mode to agents

Revision ID: 1d745494df26
Revises: 59a034566727
Create Date: 2026-04-13 10:07:18.395121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d745494df26'
down_revision: Union[str, None] = '59a034566727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('kb_retrieval_mode', sa.String(length=20), nullable=False, server_default='tool'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'kb_retrieval_mode')
    # ### end Alembic commands ###
