"""payment_provider_configs

Revision ID: af718cbf181f
Revises: 76f3806bcd90
Create Date: 2026-05-17 16:22:20.001203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af718cbf181f'
down_revision: Union[str, None] = '76f3806bcd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_provider_configs',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='both', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_test_mode', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('encrypted_secrets', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_tested_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_test_result', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_provider_configs')
    # ### end Alembic commands ###
